github: mannemiethe
custom:
  - "https://www.buymeacoffee.com/mannemiethe"
  - "https://www.paypal.com/donate/?hosted_button_id=EP53TYWA59J3G" # Maintainer/author: Manuel Miethe
  - "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=58GE7PE2EAQAY&source=url" # Original developer: Maximilian Beckenbauer
